"""empty message

Revision ID: 13e1961b2e28
Revises: a79bbe904031
Create Date: 2024-09-29 17:01:07.093047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '13e1961b2e28'
down_revision: Union[str, None] = 'a79bbe904031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('pyotp_secret', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False))
    op.add_column('user', sa.Column('pyotp_last_auth_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pyotp_last_auth_at')
    op.drop_column('user', 'pyotp_secret')
    op.drop_column('user', 'confirmed_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
