"""empty message

Revision ID: 7f67f7deeea9
Revises: 20a442f17098
Create Date: 2024-10-22 17:41:13.766267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7f67f7deeea9'
down_revision: Union[str, None] = '20a442f17098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passkey', 'challenge')
    op.add_column('user', sa.Column('webauthn_challenge', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'webauthn_challenge')
    op.add_column('passkey', sa.Column('challenge', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
